version: "2"
services:
  client:
    image: mhart/alpine-node:6.8.0
    restart: always
    ports:
      - "3000:3000"
    working_dir: /client/src/app
    volumes:
      - ./client:/client/src/app
    entrypoint: ["npm", "start"]
    links:
      - api
    networks:
      - webappnetwork
  api:
    image: webapp-api
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - mongodb
    networks:
      - webappnetwork
  db:
    image: mysql  #:5.7 or 8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL port running inside container>
      - '3306:3306'
    expose:
      # Opens port on container
      - '3306'
    volumes:
      # Where the data will be persisted
      - my-db:/var/lib/mysql
    networks: 
      - webappnetwork
  # Names our volume
  volumes:
    my-db:
  # mongodb:
  #  image: mongo
  #  restart: always
  #  container_name: mongodb
  #  volumes:
  #    - ./data-node:/data/db
  #  ports:
  #    - 27017:27017
  #  command: mongod --noauth --smallfiles
  #  networks:
  #    - webappnetwork
networks:
  webappnetwork:
    driver: bridge